version: "3.9"
services:
  app:
    build: .
    stdin_open: true
    tty: true
    pre_stop:
      - command: pip freeze > requirements.txt
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "7860:7860"
